### ISSUE TITLE
Any feedback?

### ISSUE THREAD

**Issue by staxmanade** [approvals/approvals.github.io#1]
Hey @isidore 

Sorry, I originally started as doing a single-page prototype, and ended up porting what appears to be most of the site over to github...

Would like to see a site that is easy to update/allow others to contribute to.

Take a look at [approvals.github.io](http://approvals.github.io) and let me know your thoughts.

It's a basic [Jekyll](http://jekyllrb.com) site.

Thoughts?

**Comment by isidore** [comment]
Cool. Id like more ways for new people to be able to understand approvals. Should think about moving the main domain over

**Comment by staxmanade** [comment]
I added a CNAME file for `approvaltests.com` - so in theory you should be able to re-point the domain to github, take a look at [this help page](https://help.github.com/articles/adding-a-cname-file-to-your-repository/#next-steps-configuring-dns-settings)

**Comment by staxmanade** [comment]
Shoot - when I put the CNAME file up, it takes me away from the github site - and transitions to the sourceforge site. I'll leave it for now - let me know when you get the CNAME for your domain setup.

**Comment by staxmanade** [comment]
/cc @dangilkerson - could you talk with @isidore about re-pointing the DNS to github? See https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

We will need to rename `CNAME.rename` -> `CNAME`.

Thoughts?

**Comment by staxmanade** [comment]
@isidore @dangilkerson  - any thoughts?

http://approvaltests.com/

> This space is managed by SourceForge.net. You have attempted to access a URL that either never existed or is no longer active. Please check the source of your link and/or contact the maintainer of the link to have them update their records.

**Comment by dangilkerson** [comment]
Sorry for the delay. @isidore and I have updated the DNS and pointed approvaltests.com to approvals.github.io   

Tell me if there's any other issues.

**Comment by staxmanade** [comment]
:boom:  - new site is LIVE!

**Comment by kytrinyx** [comment]
:sparkles: w00t :sparkles:
