### ISSUE TITLE
Check out the new site!

### ISSUE THREAD

**Issue by staxmanade** [approvals/approvals.github.io#2]
Hey All You @approvals/owners 

If you haven't seen or heard of the reboot of [http://approvaltests.com](http://approvaltests.com), this is a little note to let you know that:
- It has been re-written using [Jekyll](http://jekyllrb.com/) and hosted here on GitHub using GH Pages
- It was only quickly ported by myself - and am completely open for suggestions or better yet pull requests with improvements
- Please take a look through the site and help improve the documentation or any other page on the site so others who stumble upon Approvals have a good place to learn how to get started...

Happy Testing!

**Comment by kytrinyx** [comment]
It looks great!
